[[bind]]
key = "shift+enter"
mode = "-- 📌 EDITOR --"
command = "editor.action.insertLineBefore"
tags = ["action"]
doc.kind = "action"
doc.name = "open line above"
doc.description = "open a new line above and stay in editor mode"
